# mapping prefab to {iconname, scale}
MAPPING = {
    'evergreen_sparse': {'name': "evergreen_lumpy", 'draw': False},
    'bernie_active': {'name': "bernie"},
    'bernie_inactive': {'name': "bernie"},
    'bernie_big': {'name': "bernie"},
    'cave_entrance_open': {'name': 'cave_open'},
    'cave_entrance': {'name': 'cave_closed'},
    'waterplant': {"name": 'barnacle_plant'},
    'moonglass_rock': {'name': 'rock_moonglass'},
    'rock2': {'name': 'rock_gold', 'scale': 0.25},
    'moonspiderden': {'name': 'spidermoonden'},
    'dragonflyfurnace': {'name': 'dragonfly_furnace'},
    'chessjunk1': {'name': 'chessjunk'},
    'chessjunk2': {'name': 'chessjunk'},
    'chessjunk3': {'name': 'chessjunk'},
    'gravestone': {'name': 'gravestones'},
    'tentacle_pillar_hole': {'name': 'tentacle_pillar', 'scale': 0.5},
    'driftwood_tree': {'name': 'driftwood_small1'},
    'rock_avocado_bush': {'name': 'rock_avocado'},
    'moon_altar_rock_idol': {'name': 'moon_altar_idol_rock'},
    'moon_altar_rock_glass': {'name': 'moon_altar_glass_rock'},
    'moon_altar_rock_seed': {'name': 'moon_altar_seed_rock'},
    'archive_moon_statue': {'name': 'archive_moon_statue1'},
    'lucy': {'name': 'lucy_axe'},
    'monkeyisland_portal': {'name': 'monkey_island_portal'},
    'mushtree_small': {'name': 'mushroom_tree_small', 'draw': False},
    'slurtlehole': {'name': 'slurtle_den'},
    'trap_starfish': {'name': 'star_trap'},
    'moon_altar_crown': {'name': 'moon_altar_crown_piece'},
    'statuemaxwell': {'name': 'statue'},
    'homesign': {'name': 'sign'},
    'rabbithouse': {'name': 'rabbit_house'},
    'houndmound': {'name': 'hound_mound'},
    'resurrectionstatue': {'name': 'resurrect'},
    'twiggytree': {'name': 'twiggy', 'draw': False},
    'trap': {'name': 'rabbittrap'},
    'atrium_statue': {},
    'tacklestation': {},
    'telebase': {},
    'turfcraftingstation': {},
    'wardrobe': {},
    'pandoraschest': {},
    'whitespider_den': {},
    'nightmarelight': {},
    'nightmaregrowth': {},
    'nightlight': {},
    'grotto_pool_big': {'anchor': (0.5, 0.5)},
    'grotto_pool_small': {'anchor': (0.5, 0.5)},
    'toadstool_cap': {'name': 'toadstool_hole', 'anchor': (0.5, 0.5), 'scale': 0.375},
    'ancient_statue': {'name': 'statue_ruins'},
    'lightning_rod': {'name': 'lightningrod'},
    'hermithouse': {'name': 'hermitcrab_home'},
    'marsh_tree': {'name': 'marshtree', 'draw': False},
    'ancient_altar': {'name': 'tab_crafting_table'},
    'ancient_altar_broken': {'name': 'tab_crafting_table'},
    'mushtree_tall': {'name': 'mushroom_tree', 'draw': False},
    'mushtree_tall_webbed': {'name': 'mushroom_tree_webbed'},
    'archive_cookpot': {'name': 'cookpot_archive'},
    'walrus_camp': {'name': 'igloo', 'scale': 0.5},
    'moon_altar_idol': {'name': 'moon_altar_idol_piece'},
    'beebox_hermit': {'name': 'beebox_hermitcrab'},
    'archive_switch': {'name': 'archive_power_switch'},
    'archive_rune_statue': {'name': 'archive_runes'},
    'palmconetree': {'name': 'palmcone_tree', 'draw': False},
    'mermthrone': {'name': 'merm_king_carpet'},
    'rock1': {'name': 'rock', 'scale': 0.25},
    'oceantree': {'name': 'oceantree_tall'},
    'oceantree_pillar': {'name': 'oceantree_pillar_small', 'scale': 0.5},
    'watertree_pillar': {'name': 'oceantree_pillar', 'scale': 0.5},
    'moon_altar_icon': {'name': 'moon_altar_icon_piece'},
    'multiplayer_portal': {'name': 'portal_dst', 'scale': 0.5, 'anchor': (0.5, 0.5)},
    'multiplayer_portal_moonrock': {'name': 'portal_dst', 'scale': 0.5, 'anchor': (0.5, 0.5)},
    'sculptingtable': {'name': 'sculpting_station'},
    'moon_altar_seed': {'name': 'moon_altar_seed_piece'},
    'charlie_lecturn': {'name': 'charlie_lectern'},
    'moon_altar_ward': {'name': 'moon_altar_ward_piece'},
    'mermthrone_construction': {'name': 'merm_king_carpet_construction'},
    'winona_battery_low': {'name': 'winona_battery_low'},
    'lightbulb': {'name': 'bulb_plant'},
    'eyeturret': {'name': 'eyeball_turret'},
    'monkeyqueen': {'name': 'monkey_queen', 'scale': 0.5, 'anchor': (0.5, 0.5)},
    'spiderhole': {'name': 'cavespider_den'},
    'rock_petrified_tree': {'name': 'petrified_tree', 'draw': False},
    'mermwatchtower': {'name': 'merm_guard_tower'},
    'oasislake': {'name': 'oasis', 'scale': 0.5, 'anchor': (0.5, 0.5)},
    'resurrectionstone': {'name': 'resurrection_stone'},
    'moon_altar_glass': {'name': 'moon_altar_glass_piece'},
    'shell_cluster': {'name': 'singingshell_cluster'},
    'antlion_spawner': {'name': 'antlion', 'scale': 0.5},
    'crabking_spawner': {'name': 'crabking', 'scale': 0.5},
    'hermithouse': {'name': 'hermitcrab_home'},
    'hermithouse_construction1': {'name': 'hermitcrab_home2'},
    'hermithouse_construction2': {'name': 'hermitcrab_home2'},
    'hermithouse_construction3': {'name': 'hermitcrab_home2'},
    'hermithouse_pearl': {'name': 'hermitcrab_home2'},
    'buzzardspawner': {'name': 'buzzard'},
    'beequeenhive': {'scale': 0.5, 'anchor': (0.5, 0.5)},
    'boat': {'anchor': (0.5, 0.5)},
    'pigking': {'scale': 0.5, 'anchor': (0.5, 0.5)},
    'statueglommer': {},
    'wormhole': {'scale': 0.375},
    'tallbirdnest': {},
    'bananabush': {},
    'berrybush_juicy': {},
    'berrybush': {},
    'berrybush2': {},
    'bookstation': {},
    'bullkelp_plant': {},
    'cactus': {},
    'cartographydesk': {},
    'catcoonden': {},
    'glommer': {},
    'dragonflychest': {},
    'eyeplant': {},
    'chester': {},
    'iceboulder': {},
    'icebox': {},
    'icepack': {},
    'klaus_sack': {},
    'livingtree': {},
    'magician_chest': {},
    'monkeytail': {},
    'moondial': {},
    'obelisk': {},
    'reeds': {},
    'rock_flintless': {},
    'saltbox': {},
    'saltstack': {},
    'winona_catapult': {},
    'winona_spotlight': {},
    'winona_battery_low': {},
    'winona_battery_high': {},
    'wobster_den': {},
    'batcave': {},
    'pond': {'anchor': (0.5, 0.5)},
    'lava_pond': {'anchor': (0.5, 0.5)},
    'pond_cave': {'anchor': (0.5, 0.5)},
    'pond_mos': {'anchor': (0.5, 0.5)},
    'hotspring': {'anchor': (0.5, 0.5)},
    'mushroom_light': {},
    'mushroom_light2': {'name': 'mushroom_light'},
    'hermitcrab_marker': {'name': 'messagebottletreasure_marker', 'anchor': (0.5, 0.5)},
    'pirate_stash': {'anchor': (0.5, 0.5)},
    'archive_orchestrina_main': {'anchor': (0.5, 0.5)},
    'cave_exit': {'name': 'cave_open2'},
    'archive_resonator': {},
    'archive_security_desk': {},
    'atrium_light': {},
    'atrium_overgrowth': {},
    'atrium_rubble': {},
    'cave_banana_tree': {},
    'cookpot': {},
    'lichen': {},
    'monkeybarrel': {},
    'monkeyhut': {},
    'sacred_chest': {},
    'stalagmite': {},
    'stalagmite_tall': {},
}